// this code is generated by simple localization don't edit it
/*
class Language {
  final String title;
  final String settings;
  final String backup;
  final String titleError;
  final String noteError;
  final String yourTitle;
  final String yourNote;
  final String discardYourNote;
  final String discard;
  final String cancel;
  final String edit;
  final String delete;
  final String done;
  final String folderName;

  Language({
    required this.title,
    required this.settings,
    required this.backup,
    required this.cancel,
    required this.delete,
    required this.discard,
    required this.discardYourNote,
    required this.done,
    required this.edit,
    required this.folderName,
    required this.noteError,
    required this.titleError,
    required this.yourNote,
    required this.yourTitle,
  });
}

 Language AR = Language(
    title: "رف المذكرات",
    settings: "الإعدادات",
    backup: "النسخ الاحتياطي",
    cancel: "إلغاء",
    delete:  "حذف",
    discard:  "تجاهل",
    discardYourNote: "هل تريد تجاهل مذكرتك",
    done: "تم",
    edit:  "تعديل",
    folderName: "اسم المجلد",
    noteError:  "رجائا ادخل المذكرة",
    titleError: "رجائا ادخل العنوان",
    yourNote: " ادخل مذكرتك",
    yourTitle:  " العنوان",
);
 Language EN =  Language(
 title : 'title',
 settings : 'settings',
 backup : 'backup',
 titleError : 'titleError',
 noteError : 'noteError',
 yourTitle : 'yourTitle',
 yourNote : 'yourNote',
 discardYourNote : 'discardYourNote',
 discard : 'discard',
 cancel : 'cancel',
 edit : 'edit',
 delete : 'delete',
 done : 'done',
 folderName : 'folderName',
);
*/

/*final Map<String,Language> Translations = {
  "ar": AR,
  "en": EN,
} ;*/
abstract class TranslationsKeys{
  static const title = 'title';
  static const settings = 'settings';
  static const backup = 'backup';
  static const titleError = 'titleError';
  static const noteError = 'noteError';
  static const yourTitle = 'yourTitle';
  static const yourNote = 'yourNote';
  static const discardYourNote = 'discardYourNote';
  static const discard = 'discard';
  static const cancel = 'cancel';
  static const edit = 'edit';
  static const delete = 'delete';
  static const done = 'done';
  static const folderName = 'folderName';
  static const aboutContent = 'aboutContent';
  static const about= 'about';
  static const permanentDelete= 'permanentDelete';
  static const priorityNotes = 'priorityNotes';
  static const priority = 'priority';
}

class Translations {
static const List<String> supportedLocales=["ar","en"];
static const Map<String,String> ar = {
  "title": "رف المذكرات",
  "settings": "الإعدادات",
  "backup": "النسخ الاحتياطي",
  "titleError": "رجائا ادخل العنوان",
  "noteError": "رجائا ادخل المذكرة",
  "yourTitle": " العنوان",
  "yourNote": " ادخل مذكرتك",
  "discardYourNote": "هل تريد تجاهل مذكرتك",
  "discard": "تجاهل",
  "cancel": "إلغاء",
  "edit": "تعديل",
  "delete": "حذف",
  "done": "تم",
  "folderName": "اسم المجلد",
  "about": "عن التطبيق",
  "aboutContent": "مرحبًا بك في رف الملاحظات، رفيقك الموثوق لاتخاذ الملاحظات بكفاءة، وتنظيم سلس، وتصنيف بدون متاعب. يتيح هذا التطبيق منصة خالية من الفوضى وسهلة الاستخدام لتسجيل أفكارك، وملاحظاتك والمعلومات المهمة.",
  "permanentDelete":"حذف بشكل دائم",
  'priorityNotes': "مذكرات مهمة",
  'priority': "درجة الاهمية"
};
static const Map<String,String> en = {
  "title": "Note Shelf",
  "settings": "Settings",
  "backup": "Backup",
  "titleError": "Please enter your title",
  "noteError": "Please enter your note",
  "yourTitle": " Your Title",
  "yourNote": "Your Note",
  "discardYourNote": "Discard your note",
  "discard": "Discard",
  "cancel": "Cancel",
  "edit": "Edit",
  "delete": "Delete",
  "done": "Done",
  "folderName": "Folder Name",
  "about": "About",
  "aboutContent": "Welcome to Note Shelf, your reliable companion for efficient note-taking, seamless organization, and hassle-free categorization. This app is committed to empowering you with a clutter-free and intuitive platform to capture your thoughts, ideas, and important information",
  "permanentDelete":"Permanently delete",
  'priorityNotes' : "Priority Notes",
  'priority': "Priority",
};
static const Map<String, Map<String,String>> mapLocales = {"ar": ar, "en": en};
}
