// this code is generated by simple localization don't edit it
/*
class Language {
  final String title;
  final String settings;
  final String backup;
  final String titleError;
  final String noteError;
  final String yourTitle;
  final String yourNote;
  final String discardYourNote;
  final String discard;
  final String cancel;
  final String edit;
  final String delete;
  final String done;
  final String folderName;

  Language({
    required this.title,
    required this.settings,
    required this.backup,
    required this.cancel,
    required this.delete,
    required this.discard,
    required this.discardYourNote,
    required this.done,
    required this.edit,
    required this.folderName,
    required this.noteError,
    required this.titleError,
    required this.yourNote,
    required this.yourTitle,
  });
}

 Language AR = Language(
    title: "رف المذكرات",
    settings: "الإعدادات",
    backup: "النسخ الاحتياطي",
    cancel: "إلغاء",
    delete:  "حذف",
    discard:  "تجاهل",
    discardYourNote: "هل تريد تجاهل مذكرتك",
    done: "تم",
    edit:  "تعديل",
    folderName: "اسم المجلد",
    noteError:  "رجائا ادخل المذكرة",
    titleError: "رجائا ادخل العنوان",
    yourNote: " ادخل مذكرتك",
    yourTitle:  " العنوان",
);
 Language EN =  Language(
 title : 'title',
 settings : 'settings',
 backup : 'backup',
 titleError : 'titleError',
 noteError : 'noteError',
 yourTitle : 'yourTitle',
 yourNote : 'yourNote',
 discardYourNote : 'discardYourNote',
 discard : 'discard',
 cancel : 'cancel',
 edit : 'edit',
 delete : 'delete',
 done : 'done',
 folderName : 'folderName',
);
*/

/*final Map<String,Language> Translations = {
  "ar": AR,
  "en": EN,
} ;*/
abstract class TranslationsKeys {
  static const title = 'title';
  static const settings = 'settings';
  static const backup = 'backup';
  static const titleError = 'titleError';
  static const noteError = 'noteError';
  static const yourTitle = 'yourTitle';
  static const yourNote = 'yourNote';
  static const discardYourNote = 'discardYourNote';
  static const discard = 'discard';
  static const cancel = 'cancel';
  static const edit = 'edit';
  static const delete = 'delete';
  static const done = 'done';
  static const folderName = 'folderName';
  static const aboutContent = 'aboutContent';
  static const about = 'about';
  static const permanentDelete = 'permanentDelete';
  static const priorityNotes = 'priorityNotes';
  static const priority = 'priority';
  static const newFolder = 'newFolder';
  static const exit = 'exit';
  static const exitTheApp = 'exitTheApp';
  static const randomNotes = 'randomNotes';
  static const noRandomNotes = 'noRandomNotes';
  static const noNotes = 'noNotes';
  static const search = 'search';
  static const fontFamily = 'fontFamily';
  static const dataRecovery = 'dataRecovery';
  static const backupMsg = 'backupMsg';
  static const restartAppMsg = 'restartAppMsg';
  static const wrongFile = 'wrongFile';
  static const restore = 'restore';
  static const restoreOldDbMsg = 'restoreOldDbMsg';


}

class Translations {
  static const List<String> supportedLocales = ["ar", "en"];
  static const Map<String, String> ar = {
    "title": "كاف",
    "settings": "الإعدادات",
    "backup": "النسخ الاحتياطي",
    "titleError": "رجائا ادخل العنوان",
    "noteError": "رجائا ادخل المذكرة",
    "yourTitle": " العنوان",
    "yourNote": " ادخل مذكرتك",
    "discardYourNote": "هل تريد تجاهل مذكرتك",
    "discard": "تجاهل",
    "cancel": "إلغاء",
    "edit": "تعديل",
    "delete": "حذف",
    "done": "تم",
    "folderName": "اسم المجلد",
    "about": "عن التطبيق",
    "restore": "استعادة البيانات",
    "restoreOldDbMsg": "هل تريد استعادة البيانات القديمة عوضا عن هذه",
    "aboutContent": '''حول تطبيق ناف

مرحبًا بك في ناف، رفيقك الموثوق لتسجيل الملاحظات بكفاءة، وتنظيم سلس، وتصنيف بدون متاعب. يتيح هذا التطبيق منصة خالية من الفوضى وسهلة الاستخدام لتسجيل أفكارك، وملاحظاتك والمعلومات المهمة.

المميزات الرئيسية:

📂المجلدات والملاحظات المصنفة: حافظ على تنظيمك مع إمكانية إنشاء المجلدات وتصنيف الملاحظات الخاصة بك. قم بتجميع المحتوى ذي الصلة معًا، مما يجعل من السهل العثور على ما تحتاجه عندما تحتاج إليه.

✒️محرر الملاحظات سهل الاستخدام: يتيح لك محرر الملاحظات سهل الاستخدام التركيز على محتواك دون تشتيت. قم بتخصيص ملاحظاتك باستخدام الخطوط والأنماط والتنسيقات التي تناسب تفضيلاتك.

🎨 الوضع الديناميكي: استمتع بتجربة رائعة مع دعم مميزات اندرويد 12+ في الوضع الديناميكي للألوان .

🌎متعدد اللغات حاليا يدعم العربية والإنجليزية 

مميزات قادمة التي ستتم اضافتها قريبا

🔍 بحث سريع: اعثر على ملاحظات أو مجلدات معينة في لحظة باستخدام ميزة البحث الفعّالة لدينا. لا مزيد من البحث من خلال صفحات لا نهاية في سبيل العثور على ما تحتاجه بسهولة.
تعليقاتك ومساهماتك غاية في الأهمية في تشكيل مستقبل التطبيق.

🔓مفتوح المصدر وبدون إعلانات:

نؤمن بالشفافية وتوفير تجربة مستخدم سلسة. لذا، يفتخرناف بأنه مفتوح المصدر وبدون إعلانات تجارية. لا تشتت، ولا إعلانات مزعجة - فقط بيئة نظيفة وخالية من التشتيت لتعزيز إنتاجيتك.


سواء كنت طالبًا، أو محترفًا، أو فكرًا إبداعيًا، أو حتى شخصًا يحب تدوين الأفكار أثناء التنقل، ناف مصمم لتلبية احتياجاتك. اختبر حرية اتخاذ الملاحظات المنظمة بدون فوضى. قم بتنزيل ناف اليوم وانضم إلينا في تحويل طريقة التقاط وإدارة ملاحظاتك''',
    "permanentDelete": "حذف بشكل دائم",
    'priorityNotes': "مذكرات مهمة",
    'priority': "درجة الاهمية",
    "newFolder": "مجلد جديد",
    "exit": "الخروج",
    "wrongFile": "ملف خاطئ",
    "exitTheApp": "هل تريد الخروج من التطبيق",
    "randomNotes": "ملاحظات عشوائية",
    "noRandomNotes": "لا توجد أي ملاحظات في الوقت الحالي.",
    "search": "البحث",
    "fontFamily": "نوع الخط:",
    "backupMsg": "تم حفظ نسخة من قاعدة البيانات في مجلد downloads",
    "restartAppMsg": "انت بحاجة الى اعادة تشغيل التطبيق",
    "dataRecovery": "استعادة البيانات",
    "noNotes":
        "لا توجد أي ملاحظات في الوقت الحالي. لماذا لا تبدأ رحلتك بملاحظة جديدة؟"
  };
  static const Map<String, String> en = {
    "title": "NAF",
    "settings": "Settings",
    "backup": "Backup",
    "titleError": "Please enter your title",
    "noteError": "Please enter your note",
    "yourTitle": " Your Title",
    "yourNote": "Your Note",
    "discardYourNote": "Discard your note",
    "discard": "Discard",
    "cancel": "Cancel",
    "edit": "Edit",
    "delete": "Delete",
    "done": "Done",
    "folderName": "Folder Name",
    "about": "About",
    "restoreOldDbMsg": "Do you want to recover old data instead of this",
    "search" :"Search",
    "fontFamily" :"font family:",
    "restore" :"Restore",
    "backupMsg": "the backup saved in the downloads directory",
    "aboutContent":
        ''' Welcome to NAF, your reliable companion for efficient note-taking,
seamless organization, and hassle-free categorization.
This app is committed to empowering you with a clutter-free
and intuitive platform to capture your thoughts, ideas, and important information.

Key Features:

Folders and Categorized Notes: Stay organized with the ability to create folders and categorize your notes. Group related content together, making it effortless to find what you need when you need it.

✒️ User-Friendly Note Editor: Our user-friendly note editor lets you focus on your content without distractions. Customize your notes with fonts, styles, and formatting that suit your preferences.

🎨 Dynamic Mode: Enjoy with the support of android 12+ dynamic palate.

🌎Multi Language Support: now it supports Arabic and English languages

🔥 Priority Notes Page: you can find your important notes quickly

Future Features:
🔍 Quick Search: Locate specific notes or folders in an instant with our efficient search feature. No more sifting through endless pages – find what you need effortlessly.


Your feedback and contributions are invaluable in shaping the future of the app.

🔓 Open Source and Ad-Free:

We believe in transparency and providing a seamless user experience. That's why NAF is proudly open source and completely ad-free. No distractions, no invasive ads – just a clean and distraction-free environment to enhance your productivity.


Whether you're a student, professional, creative thinker, or simply someone who loves to jot down ideas on the go, NAF is designed to meet your needs. Experience the freedom of organized note-taking without the clutter. Download NAF today and join us in revolutionizing the way you capture and manage your notes.''',
    "permanentDelete": "Permanently delete",
    'priorityNotes': "Priority Notes",
    'priority': "Priority",
    "newFolder": "New Folder",
    "exit": "Exit",
    "exitTheApp": "do you want to exit the app",
    "randomNotes": "Random Notes",
    "noRandomNotes": "No notes to be found at the moment.",
    "dataRecovery": "Data recovery",
    "restartAppMsg": "you need to restart the app",
    "wrongFile": "wrong file",
    "noNotes":
        "No notes to be found at the moment. Why not begin your journey with a fresh note?"
  };
  static const Map<String, Map<String, String>> mapLocales = {
    "ar": ar,
    "en": en
  };
}
