// this code is generated by simple localization don't edit it
/*
class Language {
  final String title;
  final String settings;
  final String backup;
  final String titleError;
  final String noteError;
  final String yourTitle;
  final String yourNote;
  final String discardYourNote;
  final String discard;
  final String cancel;
  final String edit;
  final String delete;
  final String done;
  final String folderName;

  Language({
    required this.title,
    required this.settings,
    required this.backup,
    required this.cancel,
    required this.delete,
    required this.discard,
    required this.discardYourNote,
    required this.done,
    required this.edit,
    required this.folderName,
    required this.noteError,
    required this.titleError,
    required this.yourNote,
    required this.yourTitle,
  });
}

 Language AR = Language(
    title: "رف المذكرات",
    settings: "الإعدادات",
    backup: "النسخ الاحتياطي",
    cancel: "إلغاء",
    delete:  "حذف",
    discard:  "تجاهل",
    discardYourNote: "هل تريد تجاهل مذكرتك",
    done: "تم",
    edit:  "تعديل",
    folderName: "اسم المجلد",
    noteError:  "رجائا ادخل المذكرة",
    titleError: "رجائا ادخل العنوان",
    yourNote: " ادخل مذكرتك",
    yourTitle:  " العنوان",
);
 Language EN =  Language(
 title : 'title',
 settings : 'settings',
 backup : 'backup',
 titleError : 'titleError',
 noteError : 'noteError',
 yourTitle : 'yourTitle',
 yourNote : 'yourNote',
 discardYourNote : 'discardYourNote',
 discard : 'discard',
 cancel : 'cancel',
 edit : 'edit',
 delete : 'delete',
 done : 'done',
 folderName : 'folderName',
);
*/

/*final Map<String,Language> Translations = {
  "ar": AR,
  "en": EN,
} ;*/
abstract class TranslationsKeys {
  static const title = 'title';
  static const settings = 'settings';
  static const backup = 'backup';
  static const titleError = 'titleError';
  static const noteError = 'noteError';
  static const yourTitle = 'yourTitle';
  static const yourNote = 'yourNote';
  static const discardYourNote = 'discardYourNote';
  static const discard = 'discard';
  static const cancel = 'cancel';
  static const edit = 'edit';
  static const delete = 'delete';
  static const done = 'done';
  static const folderName = 'folderName';
  static const aboutContent = 'aboutContent';
  static const about = 'about';
  static const permanentDelete = 'permanentDelete';
  static const priorityNotes = 'priorityNotes';
  static const priority = 'priority';
  static const newFolder = 'newFolder';
  static const exit = 'exit';
  static const exitTheApp = 'exitTheApp';
  static const randomNotes = 'randomNotes';
  static const noRandomNotes = 'noRandomNotes';
  static const noNotes = 'noNotes';
  static const search = 'search';
  static const fontFamily = 'fontFamily';
  static const dataRecovery = 'dataRecovery';
  static const backupMsg = 'backupMsg';
  static const restartAppMsg = 'restartAppMsg';
  static const wrongFile = 'wrongFile';
  static const restore = 'restore';
  static const restoreOldDbMsg = 'restoreOldDbMsg';
  static const enterFolderName = 'enterFolderName';
  static const saveDataLocally = 'saveDataLocally';
  static const save = 'save';
}

class Translations {
  static const List<String> supportedLocales = ["ar", "en"];
  static const Map<String, String> ar = {
    "save": "حفظ",
    "title": "كاف",
    "settings": "الإعدادات",
    "backup": "النسخ الاحتياطي",
    "titleError": "رجائا ادخل العنوان",
    "noteError": "رجائا ادخل المذكرة",
    "yourTitle": " العنوان",
    "yourNote": " ادخل مذكرتك",
    "discardYourNote": "هل تريد تجاهل مذكرتك",
    "discard": "تجاهل",
    "cancel": "إلغاء",
    "edit": "تعديل",
    "delete": "حذف",
    "done": "تم",
    "folderName": "اسم المجلد",
    "saveDataLocally": "حفظ البيانات محليا",
    "about": "عن التطبيق",
    "restore": "استعادة البيانات",
    "enterFolderName": "أدخل اسم المجلد",
    "restoreOldDbMsg": "هل تريد استعادة البيانات القديمة عوضا عن هذه",
    "permanentDelete": "حذف بشكل دائم",
    'priorityNotes': "مذكرات مهمة",
    'priority': "درجة الاهمية",
    "newFolder": "مجلد جديد",
    "exit": "الخروج",
    "wrongFile": "ملف خاطئ",
    "exitTheApp": "هل تريد الخروج من التطبيق",
    "randomNotes": "ملاحظات عشوائية",
    "noRandomNotes": "لا توجد أي ملاحظات في الوقت الحالي.",
    "search": "البحث",
    "fontFamily": "نوع الخط:",
    "backupMsg": "تم حفظ نسخة من قاعدة البيانات في مجلد downloads",
    "restartAppMsg": "انت بحاجة الى اعادة تشغيل التطبيق",
    "dataRecovery": "استعادة البيانات",
    "noNotes":
        "لا توجد أي ملاحظات في الوقت الحالي. لماذا لا تبدأ رحلتك بملاحظة جديدة؟"
  };
  static const Map<String, String> en = {
    "save": "Save",
    "title": "KAF",
    "settings": "Settings",
    "backup": "Backup",
    "titleError": "Please enter your title",
    "noteError": "Please enter your note",
    "yourTitle": " Your Title",
    "yourNote": "Your Note",
    "discardYourNote": "Discard your note",
    "discard": "Discard",
    "saveDataLocally": "Save Data Locally",
    "cancel": "Cancel",
    "edit": "Edit",
    "delete": "Delete",
    "done": "Done",
    "enterFolderName": "Enter Folder Name",
    "folderName": "Folder Name",
    "about": "About",
    "restoreOldDbMsg": "Do you want to recover old data instead of this",
    "search": "Search",
    "fontFamily": "font family:",
    "restore": "Restore",
    "backupMsg": "the backup saved in the downloads directory",
    "permanentDelete": "Permanently delete",
    'priorityNotes': "Priority Notes",
    'priority': "Priority",
    "newFolder": "New Folder",
    "exit": "Exit",
    "exitTheApp": "do you want to exit the app",
    "randomNotes": "Random Notes",
    "noRandomNotes": "No notes to be found at the moment.",
    "dataRecovery": "Data recovery",
    "restartAppMsg": "you need to restart the app",
    "wrongFile": "wrong file",
    "noNotes":
        "No notes to be found at the moment. Why not begin your journey with a fresh note?"
  };
  static const Map<String, Map<String, String>> mapLocales = {
    "ar": ar,
    "en": en
  };
}
